name: guanaco-13b
model_name_or_path: /home/chj/LLMJailbreak/models/guanaco-13B-HF
tokenizer_name_or_path: /home/chj/LLMJailbreak/models/guanaco-13B-HF
device: cuda:0
dtype: float16
template: vicuna_chat
